CREATE TABLE IF NOT EXISTS tasks (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     description VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    createdAt TIMESTAMP NOT NULL
    );

INSERT INTO tasks (description, status, createdAt) VALUES
                                                       ('Estudar Domain Driven Design',
                                                        'CONCLUIDA',
                                                        CURRENT_TIMESTAMP),
                                                       ('Preparar aula de JDBC',
                                                        'PENDENTE',
                                                        CURRENT_TIMESTAMP);